name: ember
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Version and build number
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Project dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # iOS style icons
  flutter_svg: ^2.0.9
  http: ^1.3.0
  font_awesome_flutter: ^10.8.0

  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  amplify_api: ^2.0.0

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0 # Recommended lints

  # riverpod
  custom_lint:
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.3.0
  build_runner: ^2.4.0

# See https://dart.dev/tools/pub/pubspec for details

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/fonts/
    - assets/icons/
